version: '3'
services:
  geolocation-api-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: geolocation_api_development
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY_BASE=${RAILS_SECRET}
    volumes:
      - ".:/rails"
      - app-storage:/rails/storage
    depends_on:
      - geolocation-api-db
    ports:
      - "3001:3000"
    env_file:
      - .env

volumes:
  db-data:
  app-storage:
